---
- name: Test new role from within this playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: stoeps.cnxautomation.my_role
        tasks_from: main.yml
