---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: molecule-rhel9
    image: registry.access.redhat.com/ubi9/ubi:9.4-1181
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
lint: |
  set -e
  yamllint .
  ansible-lint .
